name: Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Nuekit Globally with Bun
        run: |
          bun install nuekit --global
          ls -la "$HOME/.bun/bin"

      - name: Build with Neukit
        run: |
          $HOME/.bun/bin/neu build -p

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .dist/prod
